### PR TITLE
 Add "Create Log Post" command to Post menu

### PR DESCRIPTION
**Pull request by AngeloStavrow**
This PR allows the user to create a post based on the logs from the last 24 hours (see issue #234); adding this to match the functionality in the iOS app (see PR #236).

https://user-images.githubusercontent.com/387655/232308048-86195ff1-f026-49e8-ba70-4bdb70245f4a.mov

<br>

_UPDATED: replaced screen recording to reflect changes in menu command/location._

### CODE REVIEW

**Comment by thebaer** [comment]
Looks great! My only hangup is that this menu item might be a little confusing to the uninitiated. My first impression was that it might be some fancy new kind of post the app is capable of.

So maybe we use some different text, like "Generate Log for Support", and/or put it under the Help menu? What do you think?

**Comment by AngeloStavrow** [comment]
Good callout @thebaer — let me move that!

**Comment by AngeloStavrow** [comment]
@thebaer Okay, updated the placement and name of the command (and re-uploaded a screen recording for you in the OP, too)!

**Comment by thebaer** [comment]
Awesome, thanks! That looks perfect!

**Pull request merged**
